# Generated by Django 2.2.7 on 2019-11-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='decreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='origion',
            new_name='origin',
        ),
        migrations.AlterField(
            model_name='creature',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
