# Generated by Django 2.2.7 on 2019-12-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
