# Generated by Django 2.2.7 on 2019-12-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191204_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
