# Generated by Django 2.2.7 on 2019-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191204_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='creatures',
            field=models.ManyToManyField(through='api.CartItem', to='api.Creature'),
        ),
    ]
