# Generated by Django 2.2.7 on 2019-12-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cart_creatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='creature',
            name='wig',
        ),
    ]
