# Generated by Django 2.2.7 on 2019-12-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191208_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='wig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Wig'),
            preserve_default=False,
        ),
    ]
