# Generated by Django 2.2.7 on 2019-12-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_creature_wig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='wig',
        ),
        migrations.RemoveField(
            model_name='wig',
            name='image',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='wig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.Wig'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CreatureWig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wigs', to='api.Creature')),
                ('wig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Wig')),
            ],
        ),
        migrations.AddField(
            model_name='wig',
            name='creatures',
            field=models.ManyToManyField(through='api.CreatureWig', to='api.Creature'),
        ),
    ]
