# Generated by Django 2.2.7 on 2019-12-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191209_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='wig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.Wig'),
        ),
    ]
